
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.15.0
 * Query Engine version: 85179d7826409ee107a6ba334b5e305ae3fba9fb
 */
Prisma.prismaVersion = {
  client: "6.15.0",
  engine: "85179d7826409ee107a6ba334b5e305ae3fba9fb"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  fullName: 'fullName',
  password: 'password',
  role: 'role',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  activeOrganizationId: 'activeOrganizationId',
  resetToken: 'resetToken',
  resetTokenExpiry: 'resetTokenExpiry'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  currentWebsite: 'currentWebsite',
  firmSize: 'firmSize',
  firmStory: 'firmStory',
  linkedinUrl: 'linkedinUrl',
  onboardingCompleted: 'onboardingCompleted',
  practiceAreas: 'practiceAreas',
  primaryLocation: 'primaryLocation',
  profileStatus: 'profileStatus',
  serviceAreas: 'serviceAreas',
  yearsInPractice: 'yearsInPractice',
  accountType: 'accountType',
  ownerId: 'ownerId',
  upgradeRequestToken: 'upgradeRequestToken',
  upgradeRequestedAt: 'upgradeRequestedAt'
};

exports.Prisma.ContentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  title: 'title',
  slug: 'slug',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  excerpt: 'excerpt',
  practiceArea: 'practiceArea',
  location: 'location',
  keywords: 'keywords',
  tags: 'tags',
  views: 'views',
  leads: 'leads',
  wordCount: 'wordCount',
  seoScore: 'seoScore',
  status: 'status',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ContentSectionScalarFieldEnum = {
  id: 'id',
  contentId: 'contentId',
  type: 'type',
  orderIndex: 'orderIndex',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  paystackSubscriptionId: 'paystackSubscriptionId',
  paystackCustomerId: 'paystackCustomerId',
  planName: 'planName',
  planPrice: 'planPrice',
  billingCycle: 'billingCycle',
  status: 'status',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  subscriptionId: 'subscriptionId',
  paystackReference: 'paystackReference',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  paymentMethod: 'paymentMethod',
  paidAt: 'paidAt',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.OnboardingAnalyticsScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  stepName: 'stepName',
  stepNumber: 'stepNumber',
  stepData: 'stepData',
  timeSpent: 'timeSpent',
  completedAt: 'completedAt',
  createdAt: 'createdAt'
};

exports.Prisma.UserOrganizationScalarFieldEnum = {
  userId: 'userId',
  organizationId: 'organizationId',
  role: 'role',
  joinedAt: 'joinedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  visibility: 'visibility'
};

exports.Prisma.ProjectMemberScalarFieldEnum = {
  userId: 'userId',
  projectId: 'projectId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DocumentScalarFieldEnum = {
  id: 'id',
  project_id: 'project_id',
  organization_id: 'organization_id',
  title: 'title',
  description: 'description',
  file_url: 'file_url',
  file_type: 'file_type',
  file_size: 'file_size',
  status: 'status',
  section: 'section',
  created_by: 'created_by',
  metadata: 'metadata',
  content_extracted: 'content_extracted',
  created_at: 'created_at',
  updated_at: 'updated_at',
  folderId: 'folderId'
};

exports.Prisma.FolderScalarFieldEnum = {
  id: 'id',
  name: 'name',
  organizationId: 'organizationId',
  parentId: 'parentId',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectDocumentScalarFieldEnum = {
  project_id: 'project_id',
  document_id: 'document_id',
  added_at: 'added_at',
  added_by: 'added_by'
};

exports.Prisma.ConversationDocumentScalarFieldEnum = {
  conversation_id: 'conversation_id',
  document_id: 'document_id',
  added_at: 'added_at',
  added_by: 'added_by'
};

exports.Prisma.DocumentContentScalarFieldEnum = {
  documentId: 'documentId',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmbeddingScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  vector: 'vector',
  chunkText: 'chunkText',
  chunkIndex: 'chunkIndex',
  createdAt: 'createdAt'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  projectId: 'projectId',
  isPinned: 'isPinned',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  aiAssociateId: 'aiAssociateId'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  content: 'content',
  role: 'role',
  createdAt: 'createdAt',
  userId: 'userId',
  metadata: 'metadata'
};

exports.Prisma.MessageReferenceScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  documentId: 'documentId',
  text: 'text',
  page: 'page',
  createdAt: 'createdAt'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  title: 'title',
  date: 'date',
  type: 'type',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KnowledgeBaseScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  instructions: 'instructions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  settings: 'settings'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  email: 'email',
  role: 'role',
  token: 'token',
  expiresAt: 'expiresAt',
  projectId: 'projectId',
  organizationId: 'organizationId',
  invitedById: 'invitedById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status'
};

exports.Prisma.ConversationMetaScalarFieldEnum = {
  conversationId: 'conversationId',
  instructions: 'instructions',
  settings: 'settings',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConversationActionScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  userId: 'userId',
  actionType: 'actionType',
  title: 'title',
  parameters: 'parameters',
  status: 'status',
  resultContent: 'resultContent',
  resultUrl: 'resultUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SharedMessageScalarFieldEnum = {
  id: 'id',
  sharedWorkspaceId: 'sharedWorkspaceId',
  sessionId: 'sessionId',
  content: 'content',
  role: 'role',
  userName: 'userName',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.SharedMessageReferenceScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  documentId: 'documentId',
  text: 'text',
  page: 'page',
  createdAt: 'createdAt'
};

exports.Prisma.SharedWorkspaceScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  conversationId: 'conversationId',
  createdBy: 'createdBy',
  title: 'title',
  description: 'description',
  accessMode: 'accessMode',
  isActive: 'isActive',
  expiresAt: 'expiresAt',
  passcode: 'passcode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SharedWorkspaceAccessScalarFieldEnum = {
  id: 'id',
  sharedWorkspaceId: 'sharedWorkspaceId',
  userId: 'userId',
  userEmail: 'userEmail',
  userName: 'userName',
  accessTime: 'accessTime'
};

exports.Prisma.AIAssociateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  instructions: 'instructions',
  organizationId: 'organizationId',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AssociateStepScalarFieldEnum = {
  id: 'id',
  associateId: 'associateId',
  description: 'description',
  stepOrder: 'stepOrder'
};

exports.Prisma.AssociateToolScalarFieldEnum = {
  id: 'id',
  associateId: 'associateId',
  toolId: 'toolId'
};

exports.Prisma.ProjectAssociateScalarFieldEnum = {
  associateId: 'associateId',
  projectId: 'projectId',
  addedAt: 'addedAt'
};

exports.Prisma.CanvasDocumentScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  content: 'content',
  htmlContent: 'htmlContent',
  plainText: 'plainText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventRegistrationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  institution: 'institution',
  email: 'email',
  registrationType: 'registrationType',
  competitions: 'competitions',
  hasOptedIn: 'hasOptedIn',
  optInToken: 'optInToken',
  accountCreated: 'accountCreated',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PublicationsScalarFieldEnum = {
  id: 'id',
  title: 'title'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  User: 'User',
  Organization: 'Organization',
  Content: 'Content',
  ContentSection: 'ContentSection',
  Subscription: 'Subscription',
  Payment: 'Payment',
  OnboardingAnalytics: 'OnboardingAnalytics',
  UserOrganization: 'UserOrganization',
  Project: 'Project',
  ProjectMember: 'ProjectMember',
  Document: 'Document',
  Folder: 'Folder',
  ProjectDocument: 'ProjectDocument',
  ConversationDocument: 'ConversationDocument',
  DocumentContent: 'DocumentContent',
  Embedding: 'Embedding',
  Conversation: 'Conversation',
  Message: 'Message',
  MessageReference: 'MessageReference',
  Event: 'Event',
  KnowledgeBase: 'KnowledgeBase',
  Invitation: 'Invitation',
  ConversationMeta: 'ConversationMeta',
  ConversationAction: 'ConversationAction',
  SharedMessage: 'SharedMessage',
  SharedMessageReference: 'SharedMessageReference',
  SharedWorkspace: 'SharedWorkspace',
  SharedWorkspaceAccess: 'SharedWorkspaceAccess',
  AIAssociate: 'AIAssociate',
  AssociateStep: 'AssociateStep',
  AssociateTool: 'AssociateTool',
  ProjectAssociate: 'ProjectAssociate',
  CanvasDocument: 'CanvasDocument',
  EventRegistration: 'EventRegistration',
  Publications: 'Publications'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
