// src/app/api/projects/[id]/reports/[reportId]/download/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@/prisma/client';
import { checkProjectAccess } from '@/lib/auth/authorization';
import { withAuth, withErrorHandler } from '@/lib/api/middleware';

const prisma = new PrismaClient();

// GET handler - Download report in specified format
export const GET = withErrorHandler(withAuth(async (
  request: NextRequest,
  userId: string,
  { params }: { params: Promise<{ id: string; reportId: string }> }
) => {
  const { id: projectId, reportId } = await params;
  const searchParams = request.nextUrl.searchParams;
  const format = searchParams.get('format') || 'html';

  // Check if user has access to this project
  const hasAccess = await checkProjectAccess(projectId, userId);

  if (!hasAccess) {
    return NextResponse.json(
      { error: 'Forbidden' },
      { status: 403 }
    );
  }

  // Fetch the report from message metadata
  // Report ID format: report-{timestamp}, we need to find the message with this report
  const messages = await prisma.message.findMany({
    where: {
      conversation: {
        projectId: projectId
      },
      role: 'assistant'
    },
    orderBy: {
      createdAt: 'desc'
    },
    take: 10 // Get last 10 messages to search through
  });

  // Find the message with matching report ID
  const message = messages.find(msg => {
    // Parse metadata if it's a JSON string
    const metadata = typeof msg.metadata === 'string'
      ? JSON.parse(msg.metadata)
      : msg.metadata as any;
    const hasReport = metadata?.report?.reportId === reportId;
    return hasReport;
  });

  if (!message) {
    return NextResponse.json(
      { error: 'Report not found' },
      { status: 404 }
    );
  }
  // Parse metadata if it's a JSON string
  const parsedMetadata = typeof message.metadata === 'string'
    ? JSON.parse(message.metadata)
    : message.metadata as any;
  const reportMetadata = parsedMetadata?.report;

  if (!reportMetadata || !reportMetadata.htmlContent) {
    return NextResponse.json(
      { error: 'Report content not available' },
      { status: 404 }
    );
  }

  const htmlContent = reportMetadata.htmlContent || '';
  const plainText = reportMetadata.plainText || '';

  // Determine filename
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `Review_Report_${timestamp}`;

  // Only support Word format
  if (format.toLowerCase() !== 'word' && format.toLowerCase() !== 'docx') {
    return NextResponse.json(
      { error: 'Invalid format. Only Word format is supported.' },
      { status: 400 }
    );
  }

  // Generate Word-compatible HTML
  const wordHtml = `
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <meta charset="utf-8">
  <title>Review Report</title>
  <style>
    body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; line-height: 1.6; }
    h1 { font-size: 18pt; font-weight: bold; color: #2c3e50; border-bottom: 2pt solid #3498db; padding-bottom: 6pt; }
    h2 { font-size: 14pt; font-weight: bold; color: #34495e; margin-top: 20pt; border-bottom: 1pt solid #bdc3c7; padding-bottom: 4pt; }
    h3 { font-size: 12pt; font-weight: bold; color: #7f8c8d; }
    p { margin-bottom: 10pt; }
    ul, ol { margin-left: 20pt; }
    li { margin-bottom: 6pt; }
  </style>
</head>
<body>
  ${htmlContent}
  <p style="margin-top: 30pt; padding-top: 15pt; border-top: 1pt solid #ecf0f1; color: #95a5a6; font-size: 9pt;">
    Generated by Wansom AI Legal Assistant on ${new Date().toLocaleString()}
  </p>
</body>
</html>`;

  return new NextResponse(wordHtml, {
    headers: {
      'Content-Type': 'application/vnd.ms-word',
      'Content-Disposition': `attachment; filename="${filename}.doc"`,
    },
  });
}));
