// components/content/ContentPreview.tsx
'use client'
import React from 'react'
import { ContentItem } from '@/types/content'
import SectionRenderer from './SectionRenderer'

interface ContentPreviewProps {
  content: ContentItem
  showMobileView?: boolean
}

export default function ContentPreview({ content, showMobileView = false }: ContentPreviewProps) {
  return (
    <div className={`content-preview ${showMobileView ? 'mobile-view' : 'desktop-view'}`}>
      <article className="legal-content max-w-4xl mx-auto">
        {/* Page Header */}
        <header className="content-header mb-8">
          <div className="page-meta text-sm text-gray-500 mb-2">
            {content.practiceArea && (
              <span className="practice-area">{content.practiceArea}</span>
            )}
            {content.location?.city && (
              <span className="location"> • {content.location.city}</span>
            )}
          </div>
          
          {content.status === 'draft' && (
            <div className="draft-banner bg-yellow-100 border border-yellow-300 text-yellow-800 px-4 py-2 rounded-md mb-4">
              ⚠️ This is a draft preview. Content is not yet published.
            </div>
          )}
        </header>

        {/* Content Sections */}
        <div className="content-sections space-y-6">
          {content.sections
            .sort((a, b) => a.orderIndex - b.orderIndex)
            .map(section => (
              <SectionRenderer
                key={section.id}
                section={section}
                isEditing={false}
              />
            ))}
        </div>

        {/* Page Footer */}
        <footer className="content-footer mt-12 pt-8 border-t border-gray-200">
          <div className="text-sm text-gray-500 text-center">
            <p>Generated by Wansom AI • {new Date(content.updatedAt).toLocaleDateString()}</p>
          </div>
        </footer>
      </article>
    </div>
  )
}